### ISSUE TITLE
will not work at all

### ISSUE THREAD

**Issue by Fireant456** [aarontwf/BattleNight-Core#100]
I have both the updated bukkit and plugin and all I get back when entering a command is to do the help command which I do but it gives me the same message
![2013-04-29_16 44 17](https://f.cloud.github.com/assets/1479965/441300/feec77e2-b115-11e2-9a55-912e0f615cc2.png)

**Comment by Fireant456** [comment]
here is my plugin list
-AutoBroadcast
-Authme
-BattleNight
-ChestShop
-Citizens
-ColoredSigns
-CraftBook
-DrugMeUp
-Essentials
-EssentialsGeoIP
-GAListener
-LWC
-Lift
-PermissionsEX
-Sentry
-ServerSigns
-SimpleRegionMarket
-SimpleSpleef
-TagAPI
-Vault
-Votifier
-TheWallsMinigame
-WorldEdit
-WorldGuard
-XCraftGate
-BanHammer
-dtlTraders
-iConomy
-mcMMO

**Comment by aarontwf** [comment]
What version of CraftBukkit are you using?

**Comment by Fireant456** [comment]
issue solved...
