### ISSUE TITLE
big problems

### ISSUE THREAD

**Issue by foller** [aarontwf/BattleNight-Core#102]
hi guys, I'm brazilian, my english is bad.
well, I put on my server battlenight followed all the steps, but I can not set the spawn for the red team and blue team. (/bn Bluelounge  / bn Set Bluelounge), good whenever I try from the command does not exist.
also, only quite put 1 lounge,/bn set lounge
  And this bad whik organized! I'm 12 hours trying to make this work and pluguin not work right!

**Comment by aarontwf** [comment]
Basically there are no <code>/bn set bluelounge</code>, <code>/bn set redlounge<code> commands it is as easy as <code>/bn set lounge</code>.  That will set the lobby spawn point.  Then you will need to create an arena (<code>/bn arenas create <name></code> and set some spawnpoints using the <code>/bn arenas addspawn <arena name></code>.

It is all on the quick start  guide if you want to have a read through that.  It is a lot more organized and indepth than this.  https://github.com/BattleNight/BattleNight-Core/wiki/Quick-start-guide
