### ISSUE TITLE
Support

### ISSUE THREAD

**Issue by Feetsalot** [aarontwf/BattleNight-Core#104]
I am having major trouble with the commands of Battle night. I will list them here and I hope you can help me:
1. I want a blue spawn and a red spawn to be in two different places and have the players have more than 1 lives. This means when the players die they must go back to their spawn base (Blue or Red) and continue fighting.
2. Every time I save, close y server, then reopen the waypoints are no longer there.

Hope you can help, thanks!

**Comment by aarontwf** [comment]
I am releasing a new version this week.

**Comment by Feetsalot** [comment]
Cool, will it allow you to do that and do you think you will get it out by tomorrow?

**Comment by aarontwf** [comment]
Yep, they will be there.  I will try release and upload tomorrow.

**Comment by Feetsalot** [comment]
How do you set different blue and red spawns in v 1.8?

**Comment by aarontwf** [comment]
Are you talking about the lobby or in an arena?

**Comment by aarontwf** [comment]
Duplicate issue
