### ISSUE TITLE
1.8.0 Class Config Bug

### ISSUE THREAD

**Issue by kris-chin** [aarontwf/BattleNight-Core#106]
Whenever the class config file is modified on the server, the config gets reset back to the default, I can't add new classes anymore because of this.

**Comment by alexrs98** [comment]
When you take out the 1.8.1 and fixes this bug?

**Comment by aarontwf** [comment]
When I have fixed a couple more bugs.

**Comment by Arcental** [comment]
I have this problem also. I think its best to keep backups of your current class file for now :)
