### ISSUE TITLE
Where to get the names?

### ISSUE THREAD

**Issue by alexrs98** [aarontwf/BattleNight-Core#107]
In the latest version, the format of the classes has changed and now used name, I would like to know where I can get the names of spells, weapons effects and accurate so that you can read the plugin, or you can read the ids of objects, effects and enchantments.
regards

**Comment by aarontwf** [comment]
Have a read of the wiki, I have linked the places where you can get the names and IDs.  https://github.com/BattleNight/BattleNight-Core/wiki/Configuration#classesyml
