### ISSUE TITLE
Class file compatibility with mobarena

### ISSUE THREAD

**Issue by alexrs98** [aarontwf/BattleNight-Core#108]
I have a problem, I put a mobarena on my server and the classes of these two plugins have the same names, no? Well what happens is that I can not put posters mobarena classes and leaving stripes below this plugin, also if I try to change using an external editor or plugin publishing sign, I can change, changed, and after putting back to battlenight class. It's annoying and I'll have to put different names to these two kinds of arenas.
Besides, if you put the name of a class elsewhere stripes also out of the class and can not do anything.
My idea is that you have to put in command to activate the posters and thereby can be put. For example  /bn class on and /bn class off.
Hope it is resolved soon.

**Comment by aarontwf** [comment]
Are you still having issues with this in v1.8.1?
