### ISSUE TITLE
Can't set red or blue lounge. Just lounge

### ISSUE THREAD

**Issue by cbergen1** [aarontwf/BattleNight-Core#109]
i've tryied everything in my config file and looked up videos on youtube. when i try to make a re lounge or a blue lounge, it says unknown command. typ /bn hel for more info. My arena also doesnt save, it just is affected by the tnt and is not protected

**Comment by aarontwf** [comment]
That's because there is only single lounge use '/bn set lounge'.  By arena not saving do you mean not protected?  BattleNight does not have any arena protection yet.  You will need to use another plugin to do this.

**Comment by cbergen1** [comment]
Thanks for the clarification. I saw youtube videos of other people setting more than one lounge for the blue and red team. I just made my arena a FFA arena so I don't have anymore problems.
