### ISSUE TITLE
Plugin not recognizing commands.

### ISSUE THREAD

**Issue by Arcental** [aarontwf/BattleNight-Core#111]
Sometimes the BN plugin does not recognize any of its commands (ex. /bn join, /bn set lounge, /bn help etc) it simply tells the player to type /bn help. It works after a few restarts sometimes. Its the only other plugins on my server is Essentials and WorldEdit.

Edit: I found the source of the problem which is the class file but I can't find any errors in my custom classes. :/
Edit2: I found the problem. I have an idea how to fix it but I don't know what are the correct name for those effects.
        effects: speed~1, jump_boost~4, resistance~1

**Comment by aarontwf** [comment]
You can use ID's but I have linked the page with the names on [this wiki page](https://github.com/BattleNight/BattleNight-Core/wiki/Configuration#enchantments).
