### ISSUE TITLE
Scoreboards disapearing

### ISSUE THREAD

**Issue by RaminKav** [aarontwf/BattleNight-Core#115]
My scoreboard works on the lobby, but once it starts the BN match, it just disapears and wont show up to keep the score, furthermore, players, although they are teamed up by color, still can hit other players. this wasnt an issue during the first few days i added battle night, but then this occured, please tell me if you need any more info. im using mcmmo and mob arena if that means anything, as well as battlearena plugin.

**Comment by aarontwf** [comment]
Which version are you using?

**Comment by RaminKav** [comment]
i run a 1.5.2 server CB, so i use the latest working 1.5.2 version BN v. 1.8.2

**Comment by aarontwf** [comment]
Try updating and testing with 1.5.2 on a test server.  Although listed as 1.6.2 it may run since I do not remember adding any new 1.6 API features.

**Comment by aarontwf** [comment]
Fixed in v1.11.0
