### ISSUE TITLE
Mutiple bugs

### ISSUE THREAD

**Issue by Mysterix27** [aarontwf/BattleNight-Core#116]
I created two arenas but when i got around to voting a problem occurred. Typing /bn vote "arena name" gives me an error "An arena by that name does not exist." Second problem is that when someone falls below ~5 hearts they get insta killed. Quite annoying.

**Comment by aarontwf** [comment]
1. /bn vote only works on the arenas on the voting scoreboard.  Was it on there?
2. That is a Bukkit bug which does not take armour damage into account on the damage event that brings the player to <= 0 health.

**Comment by Mysterix27** [comment]
I figured it out - i needed to write the number of the arena, not the name (silly me :D)
As for the bug I hope they fix it soon :)

Thank you for replying :)

**Comment by Mysterix27** [comment]
I have one more question tho: Is it possible to change the battle gamemode from Survival to Adventure so players can't break the arena?

**Comment by aarontwf** [comment]
I tried that but unfortunately it means players cant click on signs.
