### ISSUE TITLE
The battle doesnt start!

### ISSUE THREAD

**Issue by Misterio77** [aarontwf/BattleNight-Core#118]
hello, me and 2 friends try to play on the arena, i set everything, but even after everyone already selected a class and hit start, the battle doesnt begins!
please help

**Comment by aarontwf** [comment]
Any errors in the console?

**Comment by Misterio77** [comment]
nevermind, i reinstalled the plugin and it worked, but thanks anyway ^^

2013/10/19, LimeByte notifications@github.com:
