### ISSUE TITLE
cannot ready up in a battle

### ISSUE THREAD

**Issue by Fireant456** [aarontwf/BattleNight-Core#119]
Just as the title says that is all there is to it. Players will punch the block and it will not ready them up. Please help!!!

**Comment by Fireant456** [comment]
the iron block will not work to ready players up but the command will

**Comment by aarontwf** [comment]
Make sure ReadyBlock in config.yml is like this <code>ReadyBlock: iron-block</code> not this <code>ReadyBlock: 42</code>.

**Comment by Fireant456** [comment]
yes the issue was fixed. Thanks!
