### ISSUE TITLE
Multiple lives settings

### ISSUE THREAD

**Issue by grichecth** [aarontwf/BattleNight-Core#12]
Anyway chance of getting an option in the config to set more than one life?

**Comment by aarontwf** [comment]
Not at the moment but it is a feature that I am really keen on adding.

**Comment by aarontwf** [comment]
##### Proposed system:
- Battles will have a death and time limit
  - Whatever limit reaches its max first will end the Battle
  - Both limits will be configurable

**Comment by aarontwf** [comment]
Added in v1.6.0
