### ISSUE TITLE
Game not starting

### ISSUE THREAD

**Issue by geshsi** [aarontwf/BattleNight-Core#121]
When typing /bn ready I get the following error. How do I fix this?

21:02:02 CONSOLE: [WARNING] [Essentials] Task #11967 for Essentials v2.12.1 generated an exception
21:02:02 CONSOLE: exception executing command 'bn' in plugin BattleNight v1.10.0
21:02:02 CONSOLE: java.lang.IllegalArgumentException: n must be positive

**Comment by aarontwf** [comment]
Try a reload.

**Comment by geshsi** [comment]
when server restarts, every bn command I input, it only replies me back like this:

22:35:15 CONSOLE: [INFO] Type /bn help to show the help menu.
