### ISSUE TITLE
Multiple Arenas

### ISSUE THREAD

**Issue by aarontwf** [aarontwf/BattleNight-Core#14]
Add the ability to set multiple arenas.

**Comment by Lildirt** [comment]
Yes. This plugin needs multiple arenas, big time. I'm pretty depressed that it doesn't really.. it's the only reason why I'm not using it.. I want moar! D:

**Comment by aarontwf** [comment]
What sort of multiple arena system are you talking about?  One where you choose the arena to join or one where you are assigned to a random arena?

**Comment by Lildirt** [comment]
Choosing the arena to join.

**Comment by Veracior** [comment]
A random map system would be cool though. Have 5 maps for your arena and it randomly selects one for the combatants to play in.

**Comment by Lildirt** [comment]
Either way.
It could be random, or it could be specific.
You could make a 'Random' portal to include both of our idea's, and make the other portals for the other arena's so people can play what they want, if they so please.

**Comment by aarontwf** [comment]
It will be random with some sort of voting system (Similar to Black Ops).  Arenas will also be disable-able.
