### ISSUE TITLE
REQUEST: Disable name colour change in TAB

### ISSUE THREAD

**Issue by weja** [aarontwf/BattleNight-Core#16]
FEATURE REQUEST:

Could you make it toggleable whether the name changes to red and blue?

It's very annoying, because our moderators have red name, and it creates lots of confusion when suddenly half of the players online look like admins and moderators.

I do not want that the name changes color depending the team you are in.

**Comment by aarontwf** [comment]
Can you please tell me if the format I have changed to is alright?  Download: http://bit.ly/bnlatest

**Comment by aarontwf** [comment]
Fixed
