### ISSUE TITLE
BUG: PvP Override in whole world

### ISSUE THREAD

**Issue by weja** [aarontwf/BattleNight-Core#17]
BUG?

It also seems that BattleNight overrides PvP to true in the whole world, when I just want it to be allowed in small region with worldguard region flag. Now people can pvp in the whole world.

This also overrides the PvP entirely in other worlds where I have set multiverse pvp=allow. Anyone can PvP there even inside protected regions.

**Comment by predawnia** [comment]
Yes, confirmed.
It overrides my Towny Advanced Non-PVP plots to PVP.

Running on CB#2126

**Comment by aarontwf** [comment]
Fixed
