### ISSUE TITLE
BattleNight-Protect

### ISSUE THREAD

**Issue by aarontwf** [aarontwf/BattleNight-Core#2]
Make a Arena protection/rebuild addon.

**Comment by ghost** [comment]
Not sure how necessary this is.  Many server use WorldGuard or something similar for land protection.
My main server uses WorldGuard and then additional protection is granted by claiming the area using Towny and setting PVP/itemuse to allow for that particular town.

Not that I have any issues with a plugin becoming more inclusive, and offering features like this, but it's also important to me that any additions (such as the one referenced here) do not conflict with pre-existing methods of protection used on my servers.

**Comment by aarontwf** [comment]
I will make sure it doesn't.
