### ISSUE TITLE
Problem With the selling classes.

### ISSUE THREAD

**Issue by hiown** [aarontwf/BattleNight-Core#27]
Okay so I have quite a large problem. At the moment I have the /sell command from essentials so that they can sell things on the go. Well in battlenight you never blocked players from using other commands so they can do the /sell command and sell the items they get and make Massive ammounts of profit. So for now I have to disable battlenight till you can have this issue fixed. Please get back to me.

**Comment by aarontwf** [comment]
I am going to add a command blacklist.

**Comment by ghost** [comment]
Would a whitelist not be better? That way it will prevent any plugin commands from working whilst in the arena except the ones chosen.

Problem with the blacklist is that you can't take into account every single command out there.

**Comment by aarontwf** [comment]
Yeah I think your right.

**Comment by aarontwf** [comment]
Fixed/Added
