### ISSUE TITLE
BattleNight-Rewards Addon

### ISSUE THREAD

**Issue by aarontwf** [aarontwf/BattleNight-Core#3]
Add a rewards system using the major economy systems (i use iconomy) and items to make the Battles seem more rewarding.

**Comment by ghost** [comment]
As mentioned on a similar issue thread, you could hook into Vault for this purpose.
Vault is used by most popular economy plugins, including iConomy.

**Comment by slipcor** [comment]
let me fix that:

Vault supports the most popular plugins ;)
