### ISSUE TITLE
Enchantments

### ISSUE THREAD

**Issue by aarontwf** [aarontwf/BattleNight-Core#30]
Posted by DrewsterX:

I know Enchantments will be hard to implement because they don't have a ID but would be nice to see them.

**Comment by aarontwf** [comment]
Proposed formatting found here: http://dev.bukkit.org/server-mods/battlenight/#c323

**Comment by Tjoma** [comment]
Sorry i don't understand, How can i put enchantment on my classes ? please ^^?

**Comment by aarontwf** [comment]
You cant (not yet anyway, its coming).

**Comment by Tjoma** [comment]
K, Your plugin is amazing ! I really love it ! Thanks you so much to uploaded it :p The only thing missing is the enchants !

**Comment by Arcental** [comment]
Yeah! :D Enchants are coming to BN. That would be really nice to have.

**Comment by aarontwf** [comment]
Give this version a try and tell me what you think.  http://bit.ly/bnlatestdev
