### ISSUE TITLE
Download, BN for Bukkit #2155?

### ISSUE THREAD

**Issue by Garfield7** [aarontwf/BattleNight-Core#35]
Hello,
i can't visit the BukkitDev site from BattleNight.
"This project is currently under moderation. Please come back later.
If you find this to be in error, please notify the administrators."
This Error is since 2 or 3 days.

Second. i use the Bukkit version #2155
i can't update yet because essentials, ... are outdated and i need these Plugins.

Third. My Bukkitserver doesn't load the BattleNight. Maybe because the versions are not compatible.
So i can't use BattleNight ...

**Comment by aarontwf** [comment]
The first issue has been fixed

Most plugins will work on a newer version of CraftBukkit even if they are labled as a lower version.  Plugins will only break if they are using super outdated things (which is quite unlikely) in their plugins.

Would you be able to paste any errors you get when trying version 1.2 on start-up for the third issue.
