### ISSUE TITLE
Internal Issues?

### ISSUE THREAD

**Issue by sitebanis** [aarontwf/BattleNight-Core#37]
I just added Worldguard, CreeperHeal, MoArrows plugins. Im pretty sure these are the prob. Anyway of fixing it without having to delete these plugins? Thanks =) great plugin want it to be working

**Comment by aarontwf** [comment]
Do the errors contain stuff about signchanger and preparePlayer?

**Comment by sitebanis** [comment]
Nope it just states "An internal error occurred while attempting to perform this command" after I type in /bn join.

**Comment by aarontwf** [comment]
Strange... I just tested it now and its working fine for me with all the same plugins.  Are you using CB 1.2.5-R4.0 and BN 1.2.1?

**Comment by sitebanis** [comment]
Let me try to delete the plugin and download it again. I cant see what version I have of bn. ill be one sec. and yes im using new craftbukkit update

**Comment by sitebanis** [comment]
lul it works now, and it was the update that I needed. 0.0 it was really weird why it wasnt working. =) sorry for the inconvenience
