### ISSUE TITLE
Creating a class problem

### ISSUE THREAD

**Issue by irjr1** [aarontwf/BattleNight-Core#39]
i created 2 classes in the classes yml and then when i went back none of the classes worked then i redownloded every thing worked fine 
# BattleNight Version: 1.2.1
# Classes Configuration File
# 
# Add Classes as you wish but do not use spaces in names.
# Items are i:dxa, i=Item d=data a=Ammount.  Data and ammount are optional
# Each class must have at least 2 items, use the dummyitem if you only want 1
# The DummyItem can also be used as a spacer (examples bellow)
# Remember, potions can not be stacked
# I have made a searchable Potion ID list available at http://bit.ly/potionlist

DummyItem: 6

Classes:
    Pyro:
        Armor: 298,299,300,301
        Items: 259,46x2,6,6,6,6,6,6,373:8195
    Tank:
        Armor: 310,311,312,313
        Items: 272,6
    Swordsman:
        Armor: 306,307,308,309
        Items: 276,6,6,6,6,6,6,6,373:8233
    Archer:
        Armor: 302,303,304,305
        Items: 261,262x64,262x64
    Medic:
        Armor: 298,303,304,305
        Items: 283,6,322x4,6,373:16389,373:16389,373:16385
    Magician:
        Armor: 6,6
        Items: 268,6,373:8258,6,6,373:16388,373:16392,373:16394,373:16396
    Spy:
        Armor: 314,6
        Items: 283,373:16452,373:16452,373:16452,332x64
    Scout:
        Armor: 317,6
        Items: 373:8258,373:8258,373:8258,373:8258,373:8258,373:8258,373:8258,373:8258,283
    Infected:
    Armor: 298,299,300,201
        Items: 373:8233,373:8233,373:8233,332x10,319x5

is it my coding?

**Comment by irjr1** [comment]
i found it i tabed infected

**Comment by irjr1** [comment]
simple mistake

**Comment by MegaMinerJon** [comment]
I have that same problem...
