### ISSUE TITLE
Battlenight Sign Bug

### ISSUE THREAD

**Issue by matgar11** [aarontwf/BattleNight-Core#41]
I was playing with some friends. i have a multiverse server with essentials and battle night. when we finish the game and join a new game we can see our names on the signs already. i really have no idea what to do please help.

**Comment by aarontwf** [comment]
Yeah, that happens sometimes.  For now just replace the signs.

**Comment by matgar11** [comment]
Ok because I fixed the blue side now only the red side does that. So I should just keep replacing the signs? When do you think that will be fixed.

**Comment by aarontwf** [comment]
In the recode

**Comment by snipernyc1** [comment]
when i place a sign with the class name and ---------------------under the name, like in the videos i cant get the items in the class after i hit the sign.plz help

**Comment by aarontwf** [comment]
Just write the class name in the correct case on the first line and leave the rest blank e.g. "Tank" (without quotes).  The line will auto-generate.

**Comment by aarontwf** [comment]
You could try this dev version: http://bit.ly/bnlatestdev

**Comment by aarontwf** [comment]
Ok, I have just finished [the new dev version](http://bit.ly/bnlatestdev) which should have fixed a whole lot of bugs.

If do however find any bugs in this version please post them here.

**Comment by aarontwf** [comment]
Fixed.
