### ISSUE TITLE
Armor/Weapon/Etc Duping

### ISSUE THREAD

**Issue by JumanjiCraft** [aarontwf/BattleNight-Core#47]
When a single player joins and leaves the battle arena they are able to dupe the battlenight system and get free armor. I've had a player dupe the system to get lots of chainmail and diamond swords, diamond armor and much more.

**Comment by aarontwf** [comment]
Ok, I'll have a look at this when I get my laptop back.

**Comment by aarontwf** [comment]
Try this and let me know if it is fixed: http://bit.ly/bnlatestdev

**Comment by JumanjiCraft** [comment]
That's fixed it. The only problem now is that with a dual creative and survival world, players that join from the creative world, when they leave the arena, or finish the arena, are TP'd back to the location of the survival world (where battlenight tells them to go after the fight or arena ends) with their entire creative inventory. In other words, players are able to join from Creative, leave the arena, re-enter Survival, and have the inventory they had in creative. There are three fixes i can think of for this. 1. Prevent players from entering the arena if they aren't in the world that the arena is in. 2. Disable entering the arena per world (by world name), perhaps with a command or config setting. OR 3. allow the creation of an exit location for the arena in each world on the server.

**Comment by JumanjiCraft** [comment]
No. 3 is my least favorite as we have a lot of worlds.

**Comment by aarontwf** [comment]
Number one is possible at the moment by only adding the "battlenight.user" permission to the worlds you want people to be able to join in and make sure "UsePermissions" in the config is set to true.

**Comment by JumanjiCraft** [comment]
yeah that did it thanks! everything works swimmingly

**Comment by aarontwf** [comment]
Good to hear, I have just made a new dev version as an attempt to fix [this issue](https://github.com/BattleNight/BattleNight-Core/issues/48).  It can be downloaded with the same link.
