### ISSUE TITLE
Invisible players

### ISSUE THREAD

**Issue by HugeBoner** [aarontwf/BattleNight-Core#50]
I love the plugin, best PvP Arena plugin I found and its easy to setup, BUT it has some problems. First, sometimes even after the battle is finished, the names of the players on the class signes stay. Sometimes, when the battle starts some of the players including me, randomly become invisible. When a player joins the arena, before the battle starts he changes his mind and decides to leave. So he types /bn leave BUT he's not taken to exit spawn, instead he just stays in the lounge. Those are the problems I have. Any ides of how to fix it?

**Comment by Arcental** [comment]
The invisible player thing might be a minecraft bug. I have that same problem with the players exiting.

**Comment by aarontwf** [comment]
Invisiblity is a Minecraft or CraftBukkit bug as I get it on my server without BattleNight and BattleNight never even touches the vanish API.

**Comment by aarontwf** [comment]
Try this and let me know if it has fixed the not leaving bug: http://bit.ly/bnlatestdev

**Comment by aarontwf** [comment]
Ok, I have just finished [the new dev version](http://bit.ly/bnlatestdev) which should have fixed a whole lot of bugs.

If do however find any bugs in this version please post them here.

**Comment by aarontwf** [comment]
Closed as Invisibility is a Bukkit bug and the other issue is fixed.
