### ISSUE TITLE
Group already has permissions and yet it wont let me set waypoints?

### ISSUE THREAD

**Issue by thoresh** [aarontwf/BattleNight-Core#51]
I have added permissions (battlenight.*) to admin + owner gorups both manually and with mangaddp
And yet it will not let me set bn waypoints (do not have permission to use those commands or whatever it usually says)

If I try to add perms again (/mangaddp admin battlenight.*) it tells me that group already has those perms ... and yet they do not work?

**Comment by aarontwf** [comment]
Do you have the "UsePermissions" setting in config.yml set to true?

**Comment by thoresh** [comment]
_Face palm_ 

Thanks Lime lol
