### ISSUE TITLE
Team Color/identify

### ISSUE THREAD

**Issue by Arcental** [aarontwf/BattleNight-Core#54]
I think having something that helps players know who is on their team while in battle. Maybe something like Wool hats or something.

**Comment by aarontwf** [comment]
I think I might wait for the dyed leather hats.

**Comment by Arcental** [comment]
I see..

**Comment by aarontwf** [comment]
Don't worry I got a better way to do this for the next update :) (Secret feature).

**Comment by cbprog** [comment]
It is no secret in the patch 1.4 can be paint armor in any color, as it is now wool. :)

**Comment by aarontwf** [comment]
Haha, but it is as it is not armour or wool blocks ;)

**Comment by Arcental** [comment]
another guess is capes?

**Comment by aarontwf** [comment]
Nope, not possible without Spout/Spoutcraft

**Comment by Arcental** [comment]
Limebyte Magic is another guess.
