### ISSUE TITLE
Sign limits

### ISSUE THREAD

**Issue by cbprog** [aarontwf/BattleNight-Core#59]
Remove the limit on class signs.

**Comment by Arcental** [comment]
You can put more then 1 sign for a class, like 2 "Warrior" Class signs make it 4 Slots

**Comment by cbprog** [comment]
No matter how much, say 20, but on the plate fits 2 - it's not comfortable, it's easier to disable it.

**Comment by aarontwf** [comment]
Its more than just disabling something, I have to store the players and signs separately so this will not be looked at before the next update.

**Comment by Arcental** [comment]
Maybe you could put a function where you can link a class sign to a empty sign making it 6 slots :)

**Comment by aarontwf** [comment]
Mm, id rather do a proper solution than a hacky fix.

**Comment by Arcental** [comment]
Okay good luck with it

**Comment by aarontwf** [comment]
##### Proposed system:
- Names will be able to extend past the sign
  - They will have a limit defined in the config
  - The limit can be set to 0 to remove the limit

**Comment by Arcental** [comment]
I think the limit should be in the classes file instead so some classes can be limited

**Comment by aarontwf** [comment]
Do you mean individual limits for each class?

**Comment by cbprog** [comment]
It's certainly better than nothing. As an option - reset the time, such as a timer = 5 minutes.

**Comment by cbprog** [comment]
Players still can not be removed from the plates. More than 2 players in one class can not be selected.
1.4.0 - craftbukkit 1.3.2 rev.3

**Comment by cbprog** [comment]
I do not know whether it is possible here to spread links with screenshots, but here one well show the current problem.
http://cb.16mb.com/temp/bug.png

**Comment by aarontwf** [comment]
I see...  Will start working on a fix.  Tip: hit <code>M</code> for the markdown cheat sheet.

**Comment by aarontwf** [comment]
Give this version a try and tell me what you think.  http://bit.ly/bnlatestdev
