### ISSUE TITLE
Mob Arena Combined With BattleNight

### ISSUE THREAD

**Issue by mrcashking228** [aarontwf/BattleNight-Core#6]
Hey I just thought I should let you know. There is a huge glitch with the plugin: Mob Arena. If you join BN pick a class then join mob arena you can leave bn then leave mob arena and it will put u in the bn lobby with the class you chose and youre in neither arena so u can tp home and put the items away. im not sure how difficult this is to fix but i just thought i should let you know. Another small glitch is there will no one in BN but it will say Game in progress or somethin like that I have to forceend the game. Thanks.

**Comment by aarontwf** [comment]
Fixed
