### ISSUE TITLE
PlayerRespawnEvent + newest source

### ISSUE THREAD

**Issue by Xarias09** [aarontwf/BattleNight-Core#60]
Hi!,

I download newest source BattleNight-Core and compile it and run at my server ;) and receive after few minutes this error:

Bukkit: #2380
TagAPI: 1.7

Here is pastebin:
http://pastebin.com/tBXBZbpA

@Edit
Know issue... when i fight at arena and DIE plugin don't teleport me to spectator area but to spawn..

@Edit-2
I repair by yourself but.. i think i must let you know about it ;p

**Comment by aarontwf** [comment]
Versions on here a very unstable at times so grab a stablish version from here instead http://bit.ly/bnlatestdev

**Comment by Xarias09** [comment]
http://pastebin.com/7mvsiDuL

:P "catch exception" ?? :3 at this version you probably dont add this ;p

**Comment by aarontwf** [comment]
Sorry, I need to find some time to have a decent look at BattleNight.  There's a few mysterious bugs.
