### ISSUE TITLE
Players use item from a class then switch to another before arena starts

### ISSUE THREAD

**Issue by wrecktify** [aarontwf/BattleNight-Core#64]
So I don't know if this is preventable, but I find it to be a big flaw in the classes.  I just use the default classes and people have been loading the magician class and eating the golden apple then switching to archer and starting the match.  This gives them a huge unfair advantage.  If there is a way to strip all potion effects when the arena officially starts to prevent abuse I think it would be a good idea.

**Comment by aarontwf** [comment]
Strange, I thought I fixed that!  Ill test it tonight to see if it still exists.
