### ISSUE TITLE
Unable to fly

### ISSUE THREAD

**Issue by cbprog** [aarontwf/BattleNight-Core#68]
Noticed 1 bug after a plug-in 1.4. When the administrator (op) with option /gamemode 1, enters on the arena (/bn join), then leaves from it (/bn leave), it can't fly any more (the rest can do all). After commands /gamemode 0, / gamemode 1, everything is normal.

**Comment by aarontwf** [comment]
Give this version a try and see if it's fixed  http://bit.ly/bnlatestdev

**Comment by cbprog** [comment]
Ok, this problem solved. But I do not understand humor about it. Why player now without armor and with the trees? :)
http://cb.16mb.com/temp/humor_battlenight.png

**Comment by aarontwf** [comment]
Haha, its the new <code>Classes.yml</code> system.  The id <code>6</code>  was used as a "spacer" in the old system.  I have removed this spacer and changed it to the keyword <code>none</code>.  You can either delete your current <code>Classes.yml</code> file or fix your current one.  More details on this are on the [new wiki page](https://github.com/BattleNight/BattleNight-Core/wiki/Configuration).

**Comment by cbprog** [comment]
Well, I removed the 3 files (class, config, metric).
This is intentional, so that everyone can customize yourself?
Swordsman:
         Armour: none, none, none, none
         Items: 276e (16 ~ 1)
or did you do it because you think that the swordsman should be without armor? But the archer with a bow enchanted with knockback.
I use only 5 classes (tank, swordsman, archer, magician, medic).
But of course it would be convenient if all were dressed. :)
Now I do it manually. I will clothe him in iron armor. :)
Thanks.
&
I think this conversation is off topic. Close it. ^)

**Comment by aarontwf** [comment]
Yeah, it is a bit off-topic but...  The swordsman seemed to overpowered so I removed the armour.
