### ISSUE TITLE
Signs resetting...

### ISSUE THREAD

**Issue by wmenke** [aarontwf/BattleNight-Core#70]
For some reason, after setting the arena up and testing it with another person, upon typing /bn leave, the signs in the blue/red lobby reset and there's no longer anything on the signs. even with a reload and signing out/in, it doesn't fix it. Help?

**Comment by aarontwf** [comment]
Are the signs fully clearing or just the 3rd and 4th lines?

**Comment by wmenke** [comment]
all of them reset, except for one, and each team has 7 classes (defaults) the entire signs just go blank and don't function any longer.

**Comment by wmenke** [comment]
i'm running 1.4.2

**Comment by aarontwf** [comment]
It could be [this Minecraft bug](https://mojang.atlassian.net/browse/MC-125), a Bukkit bug or BattleNight.  But as it hasn't been happening for me I am guessing its one of the first two.  I am working on a new version which changes signs completely and will hopefully stop any clearing or non-clearing bugs.

**Comment by Realmlist** [comment]
I'm having the same problem.
The signs reset after each battle, /reload and server restart.

(MC 1.4.2 // Bukkit 1.4.2 BETA R-2.0)

**Comment by aarontwf** [comment]
Just replied on BukkitDev :smiley:.

**Comment by Realmlist** [comment]
Aight, thank you!

**Comment by aarontwf** [comment]
Give this version a try.  http://bit.ly/bnlatestdev

**Comment by Realmlist** [comment]
Signs are working like a charm, a.k.a: Fixed.
