### ISSUE TITLE
Can't submit offline player!

### ISSUE THREAD

**Issue by Realmlist** [aarontwf/BattleNight-Core#71]
So, I just finished playing with some people BN. And when we disconnected, I got this.

![Error Screenshot](http://i.imgur.com/BnegY.png)

**Comment by aarontwf** [comment]
+1 for Windows Server 2012 :smile:

**Comment by Realmlist** [comment]
Heehee. :smiley:

**Comment by aarontwf** [comment]
Try this and tell me if it's fixed.  http://bit.ly/bnlatestdev

**Comment by Realmlist** [comment]
Fixed.
