### ISSUE TITLE
Signs doesn't work

### ISSUE THREAD

**Issue by svenwbusch** [aarontwf/BattleNight-Core#73]
Howdy,

i've installed BN and it works just very fine. But i get no items when i klick on the class-signs. Is this a known problem, or do you have any idea what i could check?

Greetings,
Sven

P.s.: Good Work!!!

**Comment by Realmlist** [comment]
The signs, do they have the correct class names on them? (Case sensitive)

**Comment by aarontwf** [comment]
Also have you joined the Battle?  Are there any console errors?
