### ISSUE TITLE
Player not found

### ISSUE THREAD

**Issue by cbprog** [aarontwf/BattleNight-Core#74]
Hi LimeByte
Honestly do not know Batllenight it or not, but in the past this was not.
When a player is in the lobby, he is issued a prefix [BN], and color. If he loses are connected to the server, for some reason he remains in the list of players, it can be seen through the Tab, but on the server it is not (Prefix [BN] disappears.). Noticed it yesterday.
I have not set yet complete 1.4.7. Maybe it was already fixed?
p.s. No errors in the log
p.s.s. If you restart the game Minecraft, then the player is not visible. Temporary ghost of some sort)

**Comment by aarontwf** [comment]
This could be a Bukkit bug.

**Comment by aarontwf** [comment]
Fixed.
