### ISSUE TITLE
Cannot Load Error (Player.dat)

### ISSUE THREAD

**Issue by JumanjiCraft** [aarontwf/BattleNight-Core#75]
This error doesn't happen all the time and it only seems to happen after the server has been running for about an hour. 

http://pastie.org/5404049

Restarting the server fixes it but inevitably the error creeps back up. There's no indication of what's causing the error to occur.

**Comment by mheiden** [comment]
Same error occured on my server

"[SEVERE] Cannot load /home/minecraft/plugins/BattleNight/.PluginData/Players.dat"
http://pastebin.com/52PFqbC0

**Comment by aarontwf** [comment]
Fixed in 1.4.9.
