### ISSUE TITLE
Individual Permission Nodes

### ISSUE THREAD

**Issue by GamersCorp** [aarontwf/BattleNight-Core#77]
If possible, can individual permission nodes be implemented for /bn join, /bn leave, etc?

**Comment by Realmlist** [comment]
I can't see sense in that. Why would you disallow someone to leave a battleground?

**Comment by GamersCorp** [comment]
Well, the issue I'm having is that if people warp from my creative world via /bn join, into the arena, which is in my survival world, once they leave they keep their creative inventory. Obviously, this leads to huge amounts of diamond blocks being "stolen"

**Comment by Realmlist** [comment]
Then I think it would be better if LimeByte looks into the teleportation part of the plug-in.

**Comment by aarontwf** [comment]
Why don't you just remove the <code>battlenight.user</code> permission from the creative world?  In the future there will be no more exit waypoint which should fix this issue.

**Comment by GamersCorp** [comment]
How would I remove the permission from only the creative world? I'm using PermissionsEx

**Comment by Realmlist** [comment]
You should be able to find it [here](https://github.com/PEXPlugins/PermissionsEx/wiki/Advanced-permissions-setup#wiki-pex-multiworld).

**Comment by GamersCorp** [comment]
I fixed the issue I was having with inventories staying the same when switching from creative worlds to arenas. I fixed it by moving the arena to its own separate world. Thanks for the help though!
