### ISSUE TITLE
Additional API

### ISSUE THREAD

**Issue by rossmcnulty** [aarontwf/BattleNight-Core#84]
I'm currently working on integrating BattleNight with a plugin of mine, and I've noticed some information that might be useful to provide in the API in addition to what's already there (and it's possible that some of this might already be available and just be user error).

These are as follows:
- [x] Checking the team a player is on
- [x] Checking not just if a player is in a battle, but whether they're a spectator or fighter

And now that seems like a smaller list than I originally though. Of course, I'll just come back with more when I think of them. Thanks!

**Comment by aarontwf** [comment]
The API is not quite finished yet but those will be/are possible.

**Comment by aarontwf** [comment]
The API can be downloaded/added as a repo from https://github.com/BattleNight/BattleNight-API/tree/repo
There isn't too much documentation but the Javadocs are at http://battlenight.github.io/BattleNight-API/apidocs/
Example use can be found at https://github.com/BattleNight/DeathStrike
