### ISSUE TITLE
Sometimes not spawning back into arena.

### ISSUE THREAD

**Issue by 100Kay** [aarontwf/BattleNight-Core#85]
I've just started using this on my server, btw its a hit to all the members, and sometimes people get spawned at the server spawn. I just wanted to point that out and see maybe why this happens? I've found a way around it though. If you kill yourself, while still in battle night but not in the arena, it will spawn you there after a few suicides.

**Comment by aarontwf** [comment]
Could be a lag issue.  I'll have a look into it.
