### ISSUE TITLE
1.6 Spectator System

### ISSUE THREAD

**Issue by 100Kay** [aarontwf/BattleNight-Core#86]
I think its a great idea but it is a huge problem for people who use bows. If you are being "Ghosted" every arrow you shot will bounce off of the spectator and be rendered useless. Is there anyway to maybe take away their physical entity? Or make it so objects pass through them instead of them just being invisible?

**Comment by aarontwf** [comment]
No there isn't.  However I could offset them a little but then shooting people from behind doesn't work.

**Comment by aarontwf** [comment]
Fixed in v1.9.0
