### ISSUE TITLE
New permissions

### ISSUE THREAD

**Issue by 100Kay** [aarontwf/BattleNight-Core#87]
Could there be any way you could add the permission for someone to be a certain class in a bn arena?
Ex) battlenight.pick.%class%
Something along those lines maybe? (Sorry thats probably wrong).

**Comment by aarontwf** [comment]
There already is!  Simply add a negative permission "battlenight.class.<class name>" to the user/group you don't want using that class.

Depending on what permissions plugin you are using it would look like one of the following:

``` yaml
permissions:
    - -battlenight.class.archer
```

``` yaml
permissions:
    - !battlenight.class.archer
```

``` yaml
permissions:
    battlenight.class.archer: false
```
