### ISSUE TITLE
Scoreboards 1.5

### ISSUE THREAD

**Issue by alexrs98** [aarontwf/BattleNight-Core#95]
Could do scoreboards during battle using the new 1.5, which you put 1 point when you kill someone and you remove 1 point when you kill, may also have a countdown.
It would be something I've seen in a server:
http://imageshack.us/photo/my-images/11/20130405204848.png/
greetings

**Comment by aarontwf** [comment]
I have been wanting to do this since it was added to Minecraft.  However the API was only added to Bukkit yesterday.
