### ISSUE TITLE
Internal error occurred?

### ISSUE THREAD

**Issue by EmmettM** [aarontwf/BattleNight-Core#99]
when i type /bn join it says internal error occurred. I have two lounges set up and two spawns and an exit, what do i do?

**Comment by aarontwf** [comment]
What version of BattleNight and CraftBukkit are you using?

**Comment by SaintStrelok** [comment]
I'm having the same problem, I'm using BattleNight v1.7.0 with CraftBukkit 1.5.1-R0.2

**Comment by aarontwf** [comment]
Fixed in v1.8.0
